---
title: "forest - intro"
output:
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{forest - intro}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r, include=FALSE}
library('forest')
library('knitr')
knitr::opts_chunk$set(
  fig.width = 8, fig.height = 6, message = FALSE, eval = TRUE
)
```

## intro

```{r}
library('survival')
lung2 <- within(lung, {
  sex <- factor(sex, 1:2, c('Male', 'Female'))
  ph.ecog <- factor(ph.ecog, 0:2)
  ph.ecog2 <- factor(ph.ecog, 0:2, ordered = TRUE)
})

mod <- coxph(Surv(time, status) ~ age + sex + ph.ecog2, lung2)
clean <- cleanfp(mod)
clean_ref <- add_reference(clean, c('Age (years)', 'Sex',
                                    'ECOG performance score'))
# clean_ref <- add_reference(clean)
prep_list <- prepare_forest(clean_ref)

plot(prep_list)
```

## examples

### `survival::coxph`

```{r}
library('survival')
mod <- coxph(Surv(time, status) ~ age + factor(sex) + rx, colon)
forest(mod)
forest(mod, plotArgs = list(show_conf = TRUE, xlim = c(0, 2)))
```

### `coxphf::coxphf`

Note: add the data argument

```{r}
library('coxphf')
mod <- coxphf(Surv(time, status) ~ age + factor(sex) + rx, colon)
forest(mod, data = colon, plotArgs = list(show_conf = TRUE, xlim = c(0, 2)))
```

### `stats::glm`

```{r}
mod <- glm(vs ~ factor(gear) + mpg, mtcars, family = 'binomial')
forest(mod)
forest(mod, plotArgs = list(show_conf = TRUE))
```

### `logistf::logistf`

Note: add the data argument

```{r}
library('logistf')
mod <- logistf(vs ~ factor(gear) + factor(am), mtcars)
forest(mod, data = mtcars)
forest(mod, data = mtcars, plotArgs = list(show_conf = TRUE, logx = TRUE))
```

### `stats::fisher.test`

Note: add the data argument

```{r}
mod <- mtcars
mod[] <- lapply(mod, function(x) +grepl('1|4', x))
forest(mpg ~ ., mod, plotArgs = list(xlim = c(0, 20), show_conf = TRUE))
```

### `cmprsk::crr`

Note: add the formula and data arguments.

```{r}
library('cmprsk')
mod <- with(transplant, {
  crr(futime, as.integer(event) - 1,
      cov1 = cbind(age, model.matrix(~ sex + abo)[, -1, drop = FALSE]))
})
forest(mod, ~ age + sex + abo, transplant)
```

### `cmprsk2::crr2`

```{r}
library('cmprsk2')
mod <- crr2(Surv(futime, event(censored) == death) ~ age + sex + abo, transplant)
forest(mod, header = c('Age at dx', 'Sex', 'Blood type'))
```

## install

```{r, eval=FALSE}
# install.packages('devtools')
devtools::install_github('raredd/forest', build_vignettes = TRUE)
```

## session

```{r, eval=TRUE}
within.list(utils::sessionInfo(), loadedOnly <- NULL)
```
